package MovieTicketBookingSystem;


/**
* MovieTicketBookingSystem/AdminHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

abstract public class AdminHelper
{
  private static String  _id = "IDL:MovieTicketBookingSystem/Admin:1.0";

  public static void insert (org.omg.CORBA.Any a, MovieTicketBookingSystem.Admin that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MovieTicketBookingSystem.Admin extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MovieTicketBookingSystem.AdminHelper.id (), "Admin");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MovieTicketBookingSystem.Admin read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdminStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MovieTicketBookingSystem.Admin value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MovieTicketBookingSystem.Admin narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MovieTicketBookingSystem.Admin)
      return (MovieTicketBookingSystem.Admin)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MovieTicketBookingSystem._AdminStub stub = new MovieTicketBookingSystem._AdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MovieTicketBookingSystem.Admin unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MovieTicketBookingSystem.Admin)
      return (MovieTicketBookingSystem.Admin)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MovieTicketBookingSystem._AdminStub stub = new MovieTicketBookingSystem._AdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
