package MovieTicketBookingSystem;


/**
* MovieTicketBookingSystem/AdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

public abstract class AdminPOA extends org.omg.PortableServer.Servant
 implements MovieTicketBookingSystem.AdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("addMovie", new java.lang.Integer (1));
    _methods.put ("removeMovieSlots", new java.lang.Integer (2));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MovieTicketBookingSystem/Admin/addMovieSlots
       {
         String adminID = in.read_string ();
         MovieTicketBookingSystem.Movie movie = MovieTicketBookingSystem.MovieHelper.read (in);
         boolean $result = false;
         $result = this.addMovieSlots (adminID, movie);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // MovieTicketBookingSystem/Admin/addMovie
       {
         String adminID = in.read_string ();
         MovieTicketBookingSystem.Movie movie = MovieTicketBookingSystem.MovieHelper.read (in);
         boolean $result = false;
         $result = this.addMovie (adminID, movie);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // MovieTicketBookingSystem/Admin/removeMovieSlots
       {
         String adminID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         boolean $result = false;
         $result = this.removeMovieSlots (adminID, movieID, movieName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // MovieTicketBookingSystem/Admin/listMovieShowsAvailability
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowsAvailability (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MovieTicketBookingSystem/Admin:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Admin _this() 
  {
    return AdminHelper.narrow(
    super._this_object());
  }

  public Admin _this(org.omg.CORBA.ORB orb) 
  {
    return AdminHelper.narrow(
    super._this_object(orb));
  }


} // class AdminPOA
