package MovieTicketBookingSystem;


/**
* MovieTicketBookingSystem/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

public interface AdminOperations 
{
  boolean addMovieSlots (String adminID, MovieTicketBookingSystem.Movie movie);
  boolean addMovie (String adminID, MovieTicketBookingSystem.Movie movie);
  boolean removeMovieSlots (String adminID, String movieID, String movieName);
  String listMovieShowsAvailability (String movieName);
} // interface AdminOperations
