package MovieTicketBookingSystem;


/**
* MovieTicketBookingSystem/CustomerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

public interface CustomerOperations 
{
  boolean bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String getBookingSchedule (String customerID);
  boolean cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
} // interface CustomerOperations
