package MovieTicketBookingSystem;


/**
* MovieTicketBookingSystem/CustomerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

abstract public class CustomerHelper
{
  private static String  _id = "IDL:MovieTicketBookingSystem/Customer:1.0";

  public static void insert (org.omg.CORBA.Any a, MovieTicketBookingSystem.Customer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MovieTicketBookingSystem.Customer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MovieTicketBookingSystem.CustomerHelper.id (), "Customer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MovieTicketBookingSystem.Customer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CustomerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MovieTicketBookingSystem.Customer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MovieTicketBookingSystem.Customer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MovieTicketBookingSystem.Customer)
      return (MovieTicketBookingSystem.Customer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MovieTicketBookingSystem._CustomerStub stub = new MovieTicketBookingSystem._CustomerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MovieTicketBookingSystem.Customer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MovieTicketBookingSystem.Customer)
      return (MovieTicketBookingSystem.Customer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MovieTicketBookingSystem._CustomerStub stub = new MovieTicketBookingSystem._CustomerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
