package MovieTicketBookingSystem;

/**
* MovieTicketBookingSystem/MovieHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

public final class MovieHolder implements org.omg.CORBA.portable.Streamable
{
  public MovieTicketBookingSystem.Movie value = null;

  public MovieHolder ()
  {
  }

  public MovieHolder (MovieTicketBookingSystem.Movie initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MovieTicketBookingSystem.MovieHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MovieTicketBookingSystem.MovieHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MovieTicketBookingSystem.MovieHelper.type ();
  }

}
