package MovieTicketBookingSystem;

/**
* MovieTicketBookingSystem/ServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public MovieTicketBookingSystem.Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (MovieTicketBookingSystem.Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MovieTicketBookingSystem.ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MovieTicketBookingSystem.ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MovieTicketBookingSystem.ServerHelper.type ();
  }

}
