package MovieTicketBookingSystem;


/**
* MovieTicketBookingSystem/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movie.idl
* Friday, February 24, 2023 8:12:34 o'clock PM EST
*/

public interface ServerOperations 
{
  MovieTicketBookingSystem.Admin getAdmin ();
  MovieTicketBookingSystem.Customer getCustomer ();
  String processRequest (String input);
} // interface ServerOperations
